# The first thing that github actions need is a name key
name: My first github action
#  The second thing it needs is the on keyword telling it when to run
on: [push]
# The above line tells to run the action when a push is made to the repository
# The next thing it needs is the jobs keyword
# That tells it what to do when the action is triggered
jobs:
# Note there could be multiple jobs in a single action
# To make jobs run sequentially, we can use the dash symbol to specify a list
# Below we are going to name a job called print-hello-world
    print-hello-world:
        # The next thing we need to do is specify the type of machine to run the job on
        runs-on: ubuntu-latest
        # The next thing we need to do is specify the steps to run the job
        steps:
        # we need to specify a list of steps to run because they are executed sequentially
            - run: echo "Hello World" 
            # The above line tells the job to run the echo command to print hello world
            - run: echo "The time is $(date)"
    build-react-app:
        runs-on: ubuntu-latest
        steps:
            # using default actions to work with my repository easily
            # The line action with any configuration will just clone to current repository
            - uses: actions/checkout@v2
            # The line below tells the job to use a node setup with the version 14
            - uses: actions/setup-node@v2
              with:
                node-version: '14.17.0'
            # The below action will print node version of the repository
            - run: node -v 
            # The below line builds the project after node has been installed
            # The name keyword specifices what will be shown in the steps of our jobs instead of it being generic
            - name: Install node_modules
              run: npm install
            - name: Building the project
              run: npm run build
            - name: Logging in to vercel
              run: npm run login
            - name: Deploying to vercel
              env:
                VERCEL_ORG_ID: HvVbqzz8dd1ZKUfcgnLIV7yG
                VERCEL_PROJECT_ID: prj_KgDPETsc7Smo0HEMEOPWAkbYT7EL
              run: npm run deploy
            - name: Finished building the project
              run: echo "Done!"
            # The below action will print the tree structure of the repository
            # - run: tree

